name: example-debug
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress debug logs 📝
        uses: ./
        env:
          DEBUG: '@cypress/github-action'
        with:
          working-directory: examples/basic
