name: example-webpack
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  # ~~~~~~~~~~~~~~~~~~ Cypress v9 and below (using Legacy configuration) ~~~~~~~~~~~~~~~~~~~ #

  wait-v9:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/v9/webpack
          start: npm start
          wait-on: 'http://localhost:8080'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v10 and higher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  wait:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/webpack
          start: npm start
          wait-on: 'http://localhost:8080'
